### ISSUE TITLE
Slow performance on long files

### ISSUE THREAD

**Issue by edg2s** [zeitport/eslint-plugin-json-es#12]
Linting a file with ~30k lines takes about 6s with eslint, but ~280s with the `eslint-plugin-json-es` parser. It doesn't appear to spend longer in any specific rule, so maybe some overhead which is causing the slow down?

`eslint-plugin-json-es` parser:

```
> TIMING=1 time npx eslint tests/cases/en-big-oldparser/en-big-oldparser.json
Rule                 | Time (ms) | Relative
:--------------------|----------:|--------:
indent               |   639.483 |    54.7%
max-len              |    45.934 |     3.9%
key-spacing          |    42.217 |     3.6%
comma-style          |    39.928 |     3.4%
no-extra-parens      |    34.074 |     2.9%
no-trailing-spaces   |    30.201 |     2.6%
...
Command exited with non-zero status 1
279.81user 1.59system 4:35.25elapsed 102%CPU (0avgtext+0avgdata 300768maxresident)k
0inputs+0outputs (0major+82500minor)pagefaults 0swaps
```
Regular parser:
```
Rule               | Time (ms) | Relative
:------------------|----------:|--------:
indent             |   657.560 |    42.5%
quote-props        |   258.444 |    16.7%
quotes             |    98.567 |     6.4%
key-spacing        |    49.780 |     3.2%
max-len            |    45.074 |     2.9%
comma-style        |    44.753 |     2.9%
...
Command exited with non-zero status 1
6.41user 0.33system 0:05.18elapsed 130%CPU (0avgtext+0avgdata 392144maxresident)k
0inputs+0outputs (0major+108247minor)pagefaults 0swaps
```

**Comment by cschuller** [comment]
That's bad. I will run some performance tests...

**Comment by cschuller** [comment]
**Performance problem confirmed**
After testing and investigating the issue I found out that the `acorn.getLineInfo` method call is the problem.
The `acorn.getLineInfo` is used to fix code location information after parsing and running the rules.

It seams that the performance decrease for larger files is not linear. 🤔

**Next step**

Replace `acorn.getLineInfo` method with own implementation.

**Comment by edg2s** [comment]
It looks like `getLineInfo` takes linear time for each token, and the number of tokens is linear to the size of the document, meaning `fixTokens` is quadratic time.

I think this can be fixed by inline-ing getLineInfo and making it stateful, such that for each subsequent call, it just continues from where it left off for the last computation.

**Comment by edg2s** [comment]
This approach works for `fixTokens` where the nodes are non-overlapping, but not `fixLocation`, so only half the problem is fixed.

**Comment by edg2s** [comment]
So as I understand it, the locations need to be recomputed to account for the `({code});` wrapper, but we know pretty reliably what the effect of this wrapper is:
* Anything on the first line has the column shifted by one. We already know what is on the first line as the line result for each token is unaffected by the wrapper, so is still correct.
* Anything not on the first line is unaffected.

**Comment by edg2s** [comment]
@cschuller I think the fix in #14 is much simpler...

**Comment by cschuller** [comment]
@edg2s 
Yes we know the effect of the wrapper. The first intention was to re-use existing acorn code - my bad :-(

I will refactor the code to undo the wrapper loc.

In the meantime I implemented a line info provider that caches the position for a given input (code).
Since the input (code) does not change its pretty fast.

Let me check #14

**Comment by cschuller** [comment]
@edg2s Tested and merged your PR - Thanks a lot.
