### ISSUE TITLE
ESLint core rule "accessor-pairs" fails in JSON files

### ISSUE THREAD

**Issue by danielrentz** [zeitport/eslint-plugin-json-es#17]
When rule "accessor-pairs" is active, linting a JSON file fails with

```
Oops! Something went wrong! :(

ESLint: 7.20.0

TypeError: Cannot read property 'type' of null
Occurred while linting package.json:1
    at isPropertyDescriptor (node_modules/eslint/lib/rules/accessor-pairs.js:127:24)
    at checkObjectExpression (node_modules/eslint/lib/rules/accessor-pairs.js:325:17)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    ...
```

This rule should be disabled for JSON files in the set of recommended rules.

**Comment by cschuller** [comment]
@danielrentz 
Danke für dein Feedback.

The rule "accessor-pairs" is not useful for JSONs 😎

I took a look at the rule implementation. It has some strong expectations about the runtime context: 

```
const grandparent = node.parent.parent;
```
A null check would work here.

I will disable the rule in the recommended rules and create a new list of "non-working" eslint rules.

**Comment by danielrentz** [comment]
Danke :)
