### ISSUE TITLE
You should add "parserOptions.extraFileExtensions" to your config

### ISSUE THREAD

**Issue by Hussain-Ruhullah** [zeitport/eslint-plugin-json-es#22]
if I give the following command in terminal
eslint ./test.json --fix

I get:

0:0 error Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: test.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

WHY?

thanks in advance

**Comment by cschuller** [comment]
Hello @Hussain-Ruhullah 

Thanks for your feedback.

I am not sure if I really understand your issue, so I have some questions.

- [ ] What eslint config do you use?
- [ ] How is your project setup? I see you are using typescript-eslint/parser and a typescript config. Do you have a public repo for some code examples?

Currently I can only guess, and I suspect a config issue between typescript parser and eslint (parser).

**Comment by Hussain-Ruhullah** [comment]
Thanks you for fast reply,
you can find the package code [here](https://gitlab.com/Hussain-Ruhullah/linteverything)
use npm link command to link my project to any node project.
create a test.json file in your project and run eslint ./test.json 
please let me know if this text is not clear

**Comment by cschuller** [comment]
@Hussain-Ruhullah 
Your package is missing the `eslint` plugin configuration for the `eslint-plugin-json-es` plugin.

Take a look at the [README.md](https://github.com/zeitport/eslint-plugin-json-es) for the configuration example.

To get a full working example, you can also check out the `example` branch of this repository,
for example: https://github.com/zeitport/eslint-plugin-json-es/tree/example/get-started

**Comment by cschuller** [comment]
@Hussain-Ruhullah 
`parserOptions.extraFileExtensions` is a [configuration setting](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-use-a-framework-like-vue-that-requires-custom-file-extensions-and-i-get-errors-like-you-should-add-parseroptionsextrafileextensions-to-your-config) of the `typescript-eslint` package:

The `eslint-plugin-json-es` plugin does not automatically configure your `eslint` nor your `typescript-eslint` setup.

**Comment by Hussain-Ruhullah** [comment]
Nope, I have update the [repo ](https://gitlab.com/Hussain-Ruhullah/linteverything) I am importing this package in another react project 
than I have created a tsconfig.eslint.json ( see in [README.md](https://gitlab.com/-/ide/project/Hussain-Ruhullah/linteverything/tree/master/-/README.md/))
but it's the same

**Comment by cschuller** [comment]
@Hussain-Ruhullah 
Please check your `tsconfig.eslint.json`, it does not contain the required configuration.

The `eslint-plugin-json-es` plugin/package provides an extra **JSON parser**. 
This parser is needed, because JSON can not be parsed directly by _ESLint_ or _TypeScript_.

A configuration is needed to tell _ESLint_ that it should use a different parser (instead of the build-in), like

```
"parser": "eslint-plugin-json-es"
```

The JSON parser does not work with JavaScript of Typescript files, so we want to use the parser **only** for "*.json" files, we need this extra config:

```
"overrides": [{
        "files": ["*.json"],
        "parser": "eslint-plugin-json-es"
    }]
```

Now we can configure a set of rules that shall apply to JSON files with the `extends` and `rules` property in the override:

```
"overrides": [{
        "files": ["*.json"],
        "parser": "eslint-plugin-json-es",
        "extends": "plugin:eslint-plugin-json-es/recommended",
        "rules": {
        }
    }]
```

**Comment by Hussain-Ruhullah** [comment]
I have two linting-setup-projects
one for our react based projects and one only js-based-projects
I have used 
eslint-plugin-json-es in both of my projects (eslint-config-react & eslint-config-node)
eslint-config-react project it is working fine and lints all the JSON

this is my eslint-config-react & node

   "parserOptions": {
        "project": "./tsconfig.eslint.json",
    },
    "parser": "@typescript-eslint/parser",
    .
    .
    .
    "overrides": [{
        "files": ["*.json"],
        "parser": "eslint-plugin-json-es",
        "extends": "plugin:eslint-plugin-json-es/recommended",
        "rules": {
             "member-delimiter-style": "off"
        }

    },
```
in the other project where I want to use eslint-config-node
it says :
```
ESLint: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser. Occurred while linting C:\project\test-service\.eslintrc.json. Please see the 'ESLint' output channel for details.
```
in both of my projects I have setted everything like this 

```

**Comment by nathan-alden-sr** [comment]
@Hussain-Ruhullah How did you resolve this? I'm running into the exact same issue. It seems that something is getting confused with the ESLint override for JSON files in TypeScript projects. Here's most of my `.eslintrc.json` file:
```json
{
  "env": {
    "browser": true,
    "es2022": true,
    "jest": true
  },
  "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:@typescript-eslint/strict", "prettier"],
  "overrides": [
    {
      "files": ["*.json"],
      "extends": "plugin:eslint-plugin-json-es/recommended",
      "parser": "eslint-plugin-json-es",
      "parserOptions": {
        "project": "./tsconfig.json"
      }
    }
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest",
    "project": "./tsconfig.json",
    "sourceType": "module"
  },
  "plugins": ["react", "react-hooks", "@typescript-eslint", "prettier"],
  "rules": {
    "@typescript-eslint/dot-notation": "error",
    ...
  },
  "settings": {
    "import/resolver": {
      "typescript": {}
    },
    "react": {
      "version": "detect"
    }
  }
}
```

**Comment by cschuller** [comment]
@nathan-alden-sr 
Maybe this small copy paste error is the problem.
The "eslint-plugin-json-es" parser does not have any options, so try to remove 

```
"parserOptions": {
        "project": "./tsconfig.json"
      }
```
from the json file "override" section.

Maybe this will help. What error message to you get?

BR
Chris
