### ISSUE TITLE
Parsing error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by sam2schwab** [zeitport/eslint-plugin-json-es#39]
After doing a super simple setup to use this as the json parser in my project, every file fails with the error `Parsing error: Unexpected end of JSON input`

Here is my setup 
```jsonc
{
//...
overrides: [
    {
      files: ['*.json'],
      parser: 'eslint-plugin-json-es'
    }
  ],
}
```

and after running eslint on a simple json file 
```json
{
  "test": "paragraph"
}
```

here is the result i get :
```
[...]% yarn eslint src/test.json 
yarn run v1.22.18
$ /Users/[...]/node_modules/.bin/eslint src/test.json


[...]/src/test.json
  1:3  error  Parsing error: Unexpected end of JSON input

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.

```

**Comment by cschuller** [comment]
Hello @sam2schwab!

Do you have a public repo where I can check you complete setup?

Some ideas what to check:

1) Remove the "," after the closing "]" in the ESLint runtime config JSON
2) Have you installed "eslint-plugin-json-es" and added as a dev dependencies?
3) What version of eslint do you use?

**Comment by cschuller** [comment]
Closed due inactivity.
