### ISSUE TITLE
Check that files are valid JSON

### ISSUE THREAD

**Issue by edg2s** [zeitport/eslint-plugin-json-es#4]
Is it possible to check that files are valid JSON while using this plugin?

**Comment by cschuller** [comment]
If you use the recommended rules then it is 99% valid JSON

I want to add more rules to the recommended list to harden it.
Doing this via rules often allows using the "fix" feature.

To be 100% sure a custom rule that does a JSON.parse can be implemented. But this rule is not able to give information about the location of a problem.

As an alternative there is a eslint-plugin-json in npm, but this package works around the ESLint rule engine and you can not write custom rules.
https://github.com/zeitport/eslint-parser-json/blob/master/docs/compare-eslint-plugin-json.md

**Comment by edg2s** [comment]
I think if you are trying to write JSON, it is quite close, but there are lots of things you can do, such as using expressions that won't throw an error. I think a validator would be useful, even if it isn't as detailed.

I tried to use eslint-plugin-json (which we were using before), but because the parser has been changed for *.json files, it doesn't work in conjunction with this plugin.

**Comment by edg2s** [comment]
> To be 100% sure a custom rule that does a JSON.parse can be implemented. But this rule is not able to give information about the location of a problem.

JSON.parse appears to give the position of the error:
![image](https://user-images.githubusercontent.com/180672/101686677-4774ae80-3a61-11eb-81b7-0c72614b5092.png)

**Comment by cschuller** [comment]
@edg2s 

A new rule `@zeitport/json/use-valid-json` was added. 

Full example of an ESLint config file:

```
{
    "overrides": [{
        "files": ["*.json"],
        "parser": "@zeitport/eslint-plugin-json",
        "extends": "plugin:@zeitport/eslint-plugin-json/recommended",
        "plugins": [
            "@zeitport/eslint-plugin-json"
        ],
        "rules": {
            "@zeitport/json/use-valid-json": ["error"]
        }
    }]
}
```

**Comment by jdforrester** [comment]
Thank you!

**Comment by edg2s** [comment]
I think we can also special case the error message "Unexpected end of JSON input" to mean the error is in the last position:

```js
JSON.parse('{');
```
```
Uncaught SyntaxError: Unexpected end of JSON input
```

**Comment by cschuller** [comment]
@edg2s 
The problem is not always at the last position.

### 🌵Problem
Given invalid JSON like

```
{
```

or 

```
{  "foo": [}  }
```

Then the plugin returns this message:

```
1:1 Parsing error: Unexpected token )
```

### 💡 Explanation

Internally the given JSON `{` will be transformed to a statement `({)`.
The statement is not correct and can not be parsed by the espree (AST) parser and a generic parse error is thrown.
Custom rules are not called after a generic parser error.

### 🚀 Next steps

Maybe the validation of the JSON via a custom rule was the false approach.
I think the validation needs to be part of the JSON parser itself. I will give it a try.
If this works out then the `@zeitport/json/use-valid-json` rule will be deprecated. 😒 Sorry

**Comment by cschuller** [comment]
@edg2s 

✔ Version 1.3.0 released.

If the JSON (code) can not be parsed with the espree (AST) parser, then a `JSON.parse` is done to provide a better error message.

**Comment by edg2s** [comment]
Thanks.

I was testing some edge cases, and this input appears to throw an exception in the linter:

`{"a":3})(`

**Comment by cschuller** [comment]
@edg2s 
What is your expected outcome?


This example will result in an error.

JSON
```
{"a":3})(
```

Config
```JSON
{
    "overrides": [{
        "files": ["*.json"],
        "parser": "@zeitport/eslint-plugin-json",
        "extends": "plugin:@zeitport/eslint-plugin-json/recommended",
        "plugins": [
            "@zeitport/eslint-plugin-json"
        ],
        "rules": {
            "@zeitport/json/use-valid-json": ["error"]
        }
    }]
}
```

Result (Version 1.3)
```cli
1:8  error  Unexpected token ) in JSON at position 7  @zeitport/json/use-valid-json
```

**Comment by edg2s** [comment]
I got an exception from within ESLint rather than an error, but if it's working for you it must be something different in my config.

**Comment by cschuller** [comment]
Can you try a clean install and or post/link your config.

I have added extra unit test for the above example at
https://github.com/zeitport/eslint-plugin-json-es/blob/d2ebbe2940422660034aab08b20487c0d0e688ce/test/rules/plugin/use-valid-json.test.js#L55

**Comment by edg2s** [comment]
Here's the stack trace:
```
ESLint: 7.14.0

TypeError: Cannot read property 'range' of undefined
Occurred while linting test/fixtures/json/valid.jsonc:1
    at nodesOrTokensOverlap (node_modules/eslint/lib/source-code/source-code.js:89:38)
    at isSpaceBetween (node_modules/eslint/lib/source-code/source-code.js:106:9)
    at SourceCode.isSpaceBetweenTokens (node_modules/eslint/lib/source-code/source-code.js:504:16)
    at openerMissingSpace (node_modules/eslint/lib/rules/space-in-parens.js:132:28)
    at tokens.forEach (node_modules/eslint/lib/rules/space-in-parens.js:232:48)
    at Array.forEach (<anonymous>)
    at checkParenSpaces (node_modules/eslint/lib/rules/space-in-parens.js:222:24)
    at listeners.(anonymous function).forEach.listener (node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

**Comment by edg2s** [comment]
...so maybe try with the `space-in-parens` rule enabled

**Comment by edg2s** [comment]
Removing that rule stops the exception. We have it set to:
`"space-in-parens": [ "error", "always", { "exceptions": [ "empty" ] } ],`
