### ISSUE TITLE
Property's key casing

### ISSUE THREAD

**Issue by wonsuc** [zeitport/eslint-plugin-json-es#45]
I want to enforce to use specific cases(e.g. camelCase, snake_case...) for key names and is there any way to support this?  
I tried `'camelcase': [1, {'properties': 'always'}]` and it seems not working.

**Comment by cschuller** [comment]
@wonsuc I will check and test it out.

**Comment by cschuller** [comment]
@wonsuc
I can confirm that the ESLint 'camelcase' rule does not work with `eslint-plugin-json-es`. 

The ESLint `camelcase` rule 
- can not check "standalone" ObjectExpressions without an assignment, like `({name: "jane"});`
- it has a hardcoded exclusion of constants built in, like `A_CONSTANT`.

I will check if I can provide a PR to the ESLint project.

🌟 A new rule `json-es/use-camelcase` was added to `eslint-plugin-json-es`.
Please checkout the README.md for more details.

**🚀 A new version `1.6.0` was released today.**

Let me know if this is working for you.

👍 Thanks for opening an issues.

**Comment by wonsuc** [comment]
Cool. Thank you.
