### ISSUE TITLE
Give plugin a unique name

### ISSUE THREAD

**Issue by edg2s** [zeitport/eslint-plugin-json-es#8]
Having to prefix rules and directives with a username is difficult. It would be better if this plugin just had a unique name. It could then be published on npm as well.

Suggestions:
1. es-json / esjson
2. json-as-js

**Comment by cschuller** [comment]
Ideas:

1. es-json
2. esjon
3. json-as-js
4. json-shim
5. json-extra
6. json-join
7. json-unite
8. json-mix
9. json-es
10. json-support
11. json-util

I personally would prefer a format like eslint-plugin-json-*

@edg2s What are your top 3 picks?

**Comment by edg2s** [comment]
1 or 2
9
3

I like the idea of using “es” as that highlights the key feature: using existing eslint rules

**Comment by cschuller** [comment]
Now I need to update 50+ repositories... :-)
